import { 
    faTrashAlt as farTrashAlt,
    faEdit as farEdit,
    faCircle as farCircle
}  from '@fortawesome/free-regular-svg-icons';
import { 
    faBan as fasBan,
    faPlusCircle as fasPlusCircle,
    faMinusCircle as fasMinusCircle,
    faTimes as fasTimes,
    faArrowLeft as fasArrowLeft,
    faPhoneVolume as fasPhoneVolume,
    faAt as fasAt,
    faSearch as fasSearch,
    faAngleLeft as fasAngleLeft,
    faAngleRight as fasAngleRigth,
    faBus as fasBus,
    faSubway as fasSubway,
    faCar as fasCar,
    faFilePdf as fasFilePdf,
    faCartArrowDown as fasCartArrowDown,
    faPlus as fasPlus,
    faMinus as fasMinus,
    faChevronLeft as fasChevronLeft,
    faChevronRight as fasChevronRight,
    faChevronDown as fasChevronDown,
    faChevronUp as fasChevronUp,
    faCircle as fasCricle,
    faCheckCircle as fasCheckCircle,
    faEye as fasEye,
} from '@fortawesome/free-solid-svg-icons';

export const FA_ICONS: any = [
    farTrashAlt,
    farEdit,
    fasBan,
    fasPlusCircle,
    fasMinusCircle,
    fasTimes,
    fasArrowLeft,
    fasPhoneVolume,
    fasAt,
    fasSearch,
    fasAngleLeft,
    fasAngleRigth,
    fasBus,
    fasSubway,
    fasCar,
    fasFilePdf,
    fasCartArrowDown,
    fasPlus,
    fasMinus,
    fasChevronLeft,
    fasChevronRight,
    fasChevronDown,
    fasChevronUp,
    fasCricle,
    farCircle,
    fasCheckCircle,
    fasEye,
    fasChevronDown,
    fasChevronUp,
];

